# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'
name: $(Rev:r)

variables:
  solution: 'LogUtility.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  buildNumber: '$(Build.BuildNumber)'
  majorVersion: ''
  version: '$(majorVersion).$(buildNumber)'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
- task: FileContenttoVariable@2
  inputs:
    FilePath: 'major_version.txt'
    VariableName: 'majorVersion'
    AddNewlines: false

- task: Assembly-Info-NetFramework@2
  inputs:
    Path: '$(Build.SourcesDirectory)'
    FileNames: |
      **\AssemblyInfo.cs
      **\AssemblyInfo.vb
    InsertAttributes: true
    FileEncoding: 'auto'
    WriteBOM: false
    VersionNumber: '$(version)'
    FileVersionNumber: '$(version)'
    InformationalVersion: '$(version)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'    

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: NuGetCommand@2    
  inputs:
    command: 'pack'
    packagesToPack: '**/LogUtility.csproj;**/LogUtility.UnitTests.csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'version'     
    buildProperties: 'tags=''log4net;asynchronous;nologging;synchronous;systeminformation;wrapper;logging;utility'''

- task: NuGetAuthenticate@0
- task: NuGetToolInstaller@1
- script: dir $(Build.ArtifactStagingDirectory)
- script: nuget push -ApiKey oy2bx5tkyc3ak3mm22qqtsgktdjjjihuvldhw45jct5fra -Source https://api.nuget.org/v3/index.json $(Build.ArtifactStagingDirectory)/LogUtility.$(version).nupkg
